Add bank custom expiry in bank transfer param and bank transfer param…
veritrans/veritrans-java pull request #19
Opened 2017-01-10 06:55 UTC by adrikacang

Add cutomexpiry paramater in banktransfer request

2017-01-17 08:12 UTC, saveav commented
hi @adrikacang, please move the test file accordingly (should be in `test` folder not in `src`).

2017-01-17 08:32 UTC, adrikacang commented
@saveav affirmative

2017-01-17 08:54 UTC, saveav commented
LGTM, please help review and merge @drabiter

2017-01-17 09:34 UTC, drabiter requested changes

2017-01-17 09:34 UTC, drabiter commented on src/main/java/id/co/veritrans/mdk/v1/gateway/model/CustomExpiry.java
> +    public CustomExpiry(final Date orderTime, final Integer expiryDuration, final Unit unit) {
`orderTime` and `unit` are optional (can be not sent on the API).

2017-01-17 09:34 UTC, drabiter commented on src/test/java/id/co/veritrans/mdk/v1/integration/vtdirect/BankTransferParamTest.java
> +            date = sdf.parse("2016-12-07 11:54:12 +0700");
there should be not `catch` guard unless we want to assert the exception, so `Date date = sdf.parse("2016-12-07 11:54:12 +0700");` should be sufficient.

2017-01-17 09:34 UTC, drabiter commented on src/test/java/id/co/veritrans/mdk/v1/integration/vtdirect/BankTransferParamTest.java
> +        BankTransferRequest param = new BankTransferRequest();
`param` is less descriptive variable name.

2017-01-17 09:34 UTC, drabiter commented on src/test/java/id/co/veritrans/mdk/v1/integration/vtdirect/BankTransferParamTest.java
> +public class BankTransferParamTest {
`BankTransferRequestTest`

2017-01-17 14:54 UTC, saveav commented
wokee, thanks kak @drabiter. @adrikacang make the necessary changes pls. thankss.

2017-01-18 02:59 UTC, adrikacang commented
Okay updated. Thank you for the feedback.

2017-01-18 03:05 UTC, drabiter approved these changes

2017-01-18 03:06 UTC, merged